apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - bootstrap-app-set.yaml

patches:
  - target:
      kind: Service
      name: argocd-server
    patch: |-
      - op: add
        path: /metadata/labels/omni.sidero.dev~1workload-proxy
        value: "true"
      - op: add
        path: /metadata/labels/omni.sidero.dev~1workload-proxy-port
        value: "443"
