apiVersion: v1
kind: Service
metadata:
  name: mkdocs
  namespace: default
  annotations:
    omni-kube-service-exposer.sidero.dev/port: "50081"
    omni-kube-service-exposer.sidero.dev/label: "MkDocs"
    omni-kube-service-exposer.sidero.dev/prefix: "mkdocs"
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: mkdocs
  type: ClusterIP
