apiVersion: v1
kind: Service
metadata:
  name: mkdocs
  namespace: default
  labels:
    # These labels enable Omni Workload Proxy
    omni.sidero.dev/workload-proxy: "true"
    omni.sidero.dev/workload-proxy-port: "8000"
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: mkdocs
  type: ClusterIP
